spring.datasource.url=jdbc:oracle:thin:@//localhost:1522/XEPDB1
spring.datasource.username=MCR_C
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
