spring.application.name=manager-product-api
jwt.secret=gerartoken
jwt.expiration=180000

spring.jackson.date-format=dd/MM/yyyy
spring.jackson.time-zone=America/Sao_Paulo


# Swagger (Springdoc OpenAPI)
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs